<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xml.fa-software.com/mycim/wsdd/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://xml.fa-software.com/mycim/wsdd/" xmlns:intf="http://xml.fa-software.com/mycim/wsdd/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="DataCollectionServiceRequest">

      <wsdl:part name="dataCollection" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="DataCollectionServiceResponse">

      <wsdl:part name="DataCollectionServiceReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="DataCollectionService">

      <wsdl:operation name="DataCollectionService" parameterOrder="dataCollection">

         <wsdl:input message="impl:DataCollectionServiceRequest" name="DataCollectionServiceRequest"/>

         <wsdl:output message="impl:DataCollectionServiceResponse" name="DataCollectionServiceResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="DataCollectionServiceSoapBinding" type="impl:DataCollectionService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="DataCollectionService">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="DataCollectionServiceRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="DataCollectionServiceResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="DataCollectionServiceService">

      <wsdl:port binding="impl:DataCollectionServiceSoapBinding" name="DataCollectionService">

         <wsdlsoap:address location="http://localhost:7001/mycim2/services/DataCollectionService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
