<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xml.fa-software.com/mycim/wsdd/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://xml.fa-software.com/mycim/wsdd/" xmlns:intf="http://xml.fa-software.com/mycim/wsdd/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="TipTopSetProductServiceResponse">

      <wsdl:part name="TipTopSetProductServiceReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="TipTopSetProductServiceRequest">

      <wsdl:part name="tblPRDProductBasis" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="TipTopSetProductService">

      <wsdl:operation name="TipTopSetProductService" parameterOrder="tblPRDProductBasis">

         <wsdl:input message="impl:TipTopSetProductServiceRequest" name="TipTopSetProductServiceRequest"/>

         <wsdl:output message="impl:TipTopSetProductServiceResponse" name="TipTopSetProductServiceResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="TipTopSetProductServiceSoapBinding" type="impl:TipTopSetProductService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="TipTopSetProductService">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="TipTopSetProductServiceRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="TipTopSetProductServiceResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="TipTopSetProductServiceService">

      <wsdl:port binding="impl:TipTopSetProductServiceSoapBinding" name="TipTopSetProductService">

         <wsdlsoap:address location="http://localhost:7001/mycim2/services/TipTopSetProductService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
