<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xml.fa-software.com/mycim/wsdd/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://xml.fa-software.com/mycim/wsdd/" xmlns:intf="http://xml.fa-software.com/mycim/wsdd/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="TipTopSetMaterialServiceRequest">

      <wsdl:part name="tblMTLMaterialBasis" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="TipTopSetMaterialServiceResponse">

      <wsdl:part name="TipTopSetMaterialServiceReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="TipTopSetMaterialService">

      <wsdl:operation name="TipTopSetMaterialService" parameterOrder="tblMTLMaterialBasis">

         <wsdl:input message="impl:TipTopSetMaterialServiceRequest" name="TipTopSetMaterialServiceRequest"/>

         <wsdl:output message="impl:TipTopSetMaterialServiceResponse" name="TipTopSetMaterialServiceResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="TipTopSetMaterialServiceSoapBinding" type="impl:TipTopSetMaterialService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="TipTopSetMaterialService">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="TipTopSetMaterialServiceRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="TipTopSetMaterialServiceResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="TipTopSetMaterialServiceService">

      <wsdl:port binding="impl:TipTopSetMaterialServiceSoapBinding" name="TipTopSetMaterialService">

         <wsdlsoap:address location="http://localhost:7001/mycim2/services/TipTopSetMaterialService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
