<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xml.fa-software.com/mycim/wsdd/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://xml.fa-software.com/mycim/wsdd/" xmlns:intf="http://xml.fa-software.com/mycim/wsdd/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="GetEqpStatusServiceResponse">

      <wsdl:part name="GetEqpStatusServiceReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="GetEqpStatusServiceRequest">

      <wsdl:part name="eqpId" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="GetEqpStatusService">

      <wsdl:operation name="GetEqpStatusService" parameterOrder="eqpId">

         <wsdl:input message="impl:GetEqpStatusServiceRequest" name="GetEqpStatusServiceRequest"/>

         <wsdl:output message="impl:GetEqpStatusServiceResponse" name="GetEqpStatusServiceResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="GetEqpStatusServiceSoapBinding" type="impl:GetEqpStatusService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="GetEqpStatusService">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="GetEqpStatusServiceRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="GetEqpStatusServiceResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="GetEqpStatusServiceService">

      <wsdl:port binding="impl:GetEqpStatusServiceSoapBinding" name="GetEqpStatusService">

         <wsdlsoap:address location="http://192.168.90.160:7001/mycim2/services/GetEqpStatusService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
