<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xml.fa-software.com/mycim/wsdd/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://xml.fa-software.com/mycim/wsdd/" xmlns:intf="http://xml.fa-software.com/mycim/wsdd/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="TipTopReciveWorkOrderServiceResponse">

      <wsdl:part name="TipTopReciveWorkOrderServiceReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="TipTopReciveWorkOrderServiceRequest">

      <wsdl:part name="tblOEMOBasis" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="TipTopReciveWorkOrderService">

      <wsdl:operation name="TipTopReciveWorkOrderService" parameterOrder="tblOEMOBasis">

         <wsdl:input message="impl:TipTopReciveWorkOrderServiceRequest" name="TipTopReciveWorkOrderServiceRequest"/>

         <wsdl:output message="impl:TipTopReciveWorkOrderServiceResponse" name="TipTopReciveWorkOrderServiceResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="TipTopReciveWorkOrderServiceSoapBinding" type="impl:TipTopReciveWorkOrderService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="TipTopReciveWorkOrderService">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="TipTopReciveWorkOrderServiceRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="TipTopReciveWorkOrderServiceResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="TipTopReciveWorkOrderServiceService">

      <wsdl:port binding="impl:TipTopReciveWorkOrderServiceSoapBinding" name="TipTopReciveWorkOrderService">

         <wsdlsoap:address location="http://localhost:7001/mycim2/services/TipTopReciveWorkOrderService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
