<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xml.fa-software.com/mycim/wsdd/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://xml.fa-software.com/mycim/wsdd/" xmlns:intf="http://xml.fa-software.com/mycim/wsdd/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="HoldLotServiceRequest">

      <wsdl:part name="holdInfo" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="HoldLotServiceResponse">

      <wsdl:part name="HoldLotServiceReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="HoldLotService">

      <wsdl:operation name="HoldLotService" parameterOrder="holdInfo">

         <wsdl:input message="impl:HoldLotServiceRequest" name="HoldLotServiceRequest"/>

         <wsdl:output message="impl:HoldLotServiceResponse" name="HoldLotServiceResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="HoldLotServiceSoapBinding" type="impl:HoldLotService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="HoldLotService">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="HoldLotServiceRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="HoldLotServiceResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://xml.fa-software.com/mycim/wsdd/" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="HoldLotServiceService">

      <wsdl:port binding="impl:HoldLotServiceSoapBinding" name="HoldLotService">

         <wsdlsoap:address location="http://192.168.90.160:7001/mycim2/services/HoldLotService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
